/*
** Generated by WorkShop Visual
*/
#ifndef _LiteClue_test_h
#define _LiteClue_test_h

#define XD_MOTIF




extern Widget CopyShell;
extern Widget CopyForm;
extern Widget CopyLabel;
extern Widget CopyOkBtn;

extern Widget LiteClueTestShell;
extern Widget MainForm;
extern Widget FileCascade;
extern Widget FileMenu;
extern Widget FileOpenBtn;
extern Widget FileExitBtn;
extern Widget EditCascade;
extern Widget EditMenu;
extern Widget EditCutBtn;
extern Widget EditCopyBtn;
extern Widget EditPasteBtn;
extern Widget HelpCascade;
extern Widget HelpMenu;
extern Widget HelpAboutBtn;
extern Widget QuitButton;
extern Widget ToolbarFrame;
extern Widget ToolbarForm;
extern Widget ToolbarOpenBtn;
extern Widget ToolbarCopyBtn;
extern Widget ToolbarExitBtn;

extern void create_CopyShell (Widget);

extern void create_LiteClueTestShell (Display *display, char *app_name, int app_argc, char **app_argv)
;

#endif
