/*
** Generated by WorkShop Visual
*/
/*
**LIBS: -lXm -lXt -lX11
*/

#include <X11/Xatom.h>
#include <X11/Intrinsic.h>
#include <X11/Shell.h>

#include <Xm/Xm.h>
#include <X11/StringDefs.h>
#include <Xm/CascadeB.h>
#include <Xm/DialogS.h>
#include <Xm/Form.h>
#include <Xm/Frame.h>
#include <Xm/Label.h>
#include <Xm/PushB.h>
#include <Xm/RowColumn.h>
#include <Xm/XpmP.h>
#include <stdio.h>
#include <stdlib.h>

#include "LiteClue_testP.h"
#include "LiteClue_test.h"

extern void CopyOkBtn_cb(Widget, XtPointer, XtPointer) ;
extern void QuitButton_cb(Widget, XtPointer, XtPointer) ;
extern void EditCopyBtn_cb(Widget, XtPointer, XtPointer) ;
Widget CopyShell = (Widget) NULL;
Widget CopyForm = (Widget) NULL;
Widget CopyLabel = (Widget) NULL;
Widget CopyOkBtn = (Widget) NULL;
Widget LiteClueTestShell = (Widget) NULL;
Widget MainForm = (Widget) NULL;
Widget FileCascade = (Widget) NULL;
Widget FileMenu = (Widget) NULL;
Widget FileOpenBtn = (Widget) NULL;
Widget FileExitBtn = (Widget) NULL;
Widget EditCascade = (Widget) NULL;
Widget EditMenu = (Widget) NULL;
Widget EditCutBtn = (Widget) NULL;
Widget EditCopyBtn = (Widget) NULL;
Widget EditPasteBtn = (Widget) NULL;
Widget HelpCascade = (Widget) NULL;
Widget HelpMenu = (Widget) NULL;
Widget HelpAboutBtn = (Widget) NULL;
Widget QuitButton = (Widget) NULL;
Widget ToolbarFrame = (Widget) NULL;
Widget ToolbarForm = (Widget) NULL;
Widget ToolbarOpenBtn = (Widget) NULL;
Widget ToolbarCopyBtn = (Widget) NULL;
Widget ToolbarExitBtn = (Widget) NULL;

#include <X11/xpm.h>

static int _xd_initialised = 0;

typedef struct PixmapResources_s { 
	Pixmap kat;
	Pixmap exit_in;
	Pixmap exit;
	Pixmap copy_in;
	Pixmap copy;
	Pixmap open_in;
	Pixmap open;
} PixmapResources_t, *PixmapResources_p;

static PixmapResources_t pixmap_resources;

static char *kat_icon [] = { 
"160 120 32 1",
"  c #000000",
". c #AB25E1",
"o c #A93DCE",
"O c #811CAA",
"a c #1F0828",
"b c #9E22D0",
"c c #FEE9FF",
"d c #A824DD",
"e c #B026E8",
"f c #921FC0",
"g c #9B21CC",
"h c #A523D9",
"i c #7C1AA3",
"j c #CCCCCC",
"k c #8D1EBA",
"l c #A626D9",
"m c #641584",
"n c #B670C7",
"p c #76199C",
"q c #B628EF",
"r c #48105E",
"s c #C6A4CC",
"t c #891DB5",
"u c #6A168C",
"v c #360B48",
"w c #8A20B5",
"x c #851DAF",
"y c #54126E",
"z c #5C1479",
"A c #9721C7",
"B c #A123D4",
"C c #711894",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnfbosjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjniBeqojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzxBqqesjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsribqqenjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnnjjjjjjjjjjjjjjjjjjjjjjjjjjsrigqqqnjjjjjjjjjssjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjfzyinsjjjjjjjjjjjjjjjjjjjjjjsvpAqqqojjjjjjsnwiwjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsAxuvazunnjjjjjjjjjjjjjjjjjjjjrCfqqqljjssoimymuCjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnxfOCyvaavzwnsjjjjjjjjjjjjjjjjrufenqqozavryzuumrsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjotftOCmraaaavyConjjjjjjjjjjjjjzOflwzavvryzmuuuzvnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjkkfkxipuzvaaaaaavyinnssnsnssnowyvaavrryzzmuuumzaCjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsOkfktxipumyvaaavymiCxkwkkffffOkuzrrryzzmmuuuumyarjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnpkffkxOipCmzyzpOxtkffAAggbbbbbbggAfiummmuuuumzyarsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjopkffktxOipmCixtkfAAggbBBBhhhhhhhhhhBgfOCuuummzyaanjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjoikffkktiuCixtkfAAgbBBhhhddd.........dhBgxCummzyaawjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjtOkfffxuCiOtkfAAgbbBhhhdd....eeeeeeeee..dhbOuzzraaCjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnpOkffiuCixtkfAAgbBBhhdd....eeeeeeeeeeeeee..hfuzyaarsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnuOkfCupixwkfAggbBBhhdd...eeeeeeqqqqqqqqqqee.dbiraaanjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjoCxkCupixtkfAAgbBBhhdd...eeeeeeqqqqqqqqqqqqqee.Bpaaanjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjwpxympixuyOAAgbbBhhfOd...eeeeeqqkqqqqqqqqqByBqe.hCvaojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjppzmCiOtkfymggbBBhfa v...eeeeqha aqqqqqqqiyqqqqeehCazsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnpzzupOxtkfAprkbBBhz   ..eeeeqqO   lqqqqimtqqqqqqe.Byvsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnmyuCiOtpmmCAgurkBhta r..eeeqqqqa reqq.vywqqqqqqqqe.banjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjtrzCpOxtkfftCmpbCBhhdd..xpmvyOAqqnnnnivOqqqqqqqqqqqedCwjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjpymCiOxtkffAAgfppxrzddxa       voscnrnsqqqqqqqqqqqqe.Bpjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjszzupiOxtkffAAgbbBpiyCv           rancccsnqqqqqqqqqqqedlsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnrmupiOxtkffAAggbBBBAa        a    mcccccsqqqqqqqqqqqe.Bsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjmymCpiOxtkffAAggbbBBO        rnsv   jccccsnqqqqqqqqqqe.hnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrymCpiOxtkffAAAgbbBBv        vnsy   rccccsnqqqqqqqqqqe.hAjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvymCpiOxryvmyyryrrvv          aa    ayyyywzCwipmmqqqee.hojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrymCpiOxtpuuyCiCCppxa               rsnooCoippxqqqqeee.hAjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsrymupiuyCtkkffAAAggbv               oqqqqqqqqqeeeeeee..hAsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvymuCpiOxtwkfffAAAggp              vqqqqqqqqeeeeeeee..dBAsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvyzuCpiOOxtkkfffAAAgwa            avweeeeeeeeeeeeee..dhBfsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvyzmuCpiOxxtkkfffAAprtua        ay.krm..............dhBgksjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvrymuCpiiOxxtkkffCvxAggkuv    ayfhhddzyx..........ddhhbAxjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrryzmuCpiOOxttkiryfAAAAggga z vBBhhhhhuvvAddddddddhhBbgfwjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvrzmuCppiOOxpzvOkfffAAAgy vbavuBBBBhhhAuCzhhhhhhhhBbgAtnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvryzmuCppiOmvztwkkfffAAmaaggp aubBBBBBBBzxpuhhBBBbbgAkisjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzvryzmuCpivvpxxttkkkffr axAAgravrbbbbBBBBupizBbbbgAAkxnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnaryzmuuCpziOOxxxiuuva aOfAAAAr vavugbbbbbOfbgggAAfkxpsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjmvryzmuuCppiiOOia    ykfffffAAya aaavgggggggAAAffkxinjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvvryzmmuCCpiiOra ayiwkkkfffffftvaaapAAAAAAAfffktximsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvvryzmmuCCppiumuOxxxttwkkkkfffffxxffffffffkktxOipsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnavryzzmuuCCppiiOOOxxxxtttwkkkkkkkkkkkkkkwtxOipmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnavryyzmmuuCCppiiiOOOxxxxxttttttttttttxxxOipCmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvvrryzzmmuuCCpppiiiOOOOOxxxxxxxxxxxOOOipCuznjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvvvryyzzmmuuCCCpppiiiiiiOOOOOOOiiiippCumysjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrvvrryyzzmmuuuCCCCppppppppppppppCCCumzCsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsrvvrryyzzzmmmuuuuCCCCCCCCCCCuuumzyynjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsnavvrrryyyzzzmmmmmuuuuuummmmzzyriojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnyavvrrryyyyzzzzzzzzzzzyyrrypqqgjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsnravvvvrrrrrrrrrrrrrvrrmklqqbsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjraaaaavvvvvvvvvvaamjzzxlqqBjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsaaaaaaaaavvryymOiOkjnyxBqqdsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnavyzutfwbBhd....dBAsnyObqq.sjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrrzupOtfAbBhd.....hAnsrigqq.ojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvrzupOtfAbBhd.....hgAsvpAeqenjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvymCixwfAbBhd.....dBAsrCA.qeAjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzrymCixkfAbBhd.....dBAorufdqeojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsnnnnvrzupixkfAbBhd.....dhgACOlqqqgjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnOOAdBCvyzupOxkfAbBhd......hbfwonccndjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnzCxAdttmymCpOxkfAbBhdd.....dBxitbqscnnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjCympxAfAAkzmCiOtkfAbBhdd.....dBupxfb.qqqnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnrzCOkAgbbgxuCiOtkfAbBhhd.....dOCitfgB.qqqnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvyuitAbhhhhbCpixtkfAbBhhd.....BmpOkAbhh.qqqsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzrmpxfghd..dhApixtfAAbBhhd.....Cuixfghd...eqnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvyuitABd.ee.dBxOxwfAAbBBhdd...xmCiwABd.ee..eesjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzrzCOkgh.eeee.hgOxkfAAbBBhdd...umCOkAB.eeee...ojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvrmpxfbdeeqqqedBkxkfAAbBBhdd..Azupxkgh.eqqqeddojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvyuptABdeqqqqe.hgxkfAAbBBhdd..mzupxfgh.qqqqe.BBsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzrzuitAB.eqqqqe.hbtkfAAgbBhe..fyzuixfbheqqqqq.hbnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjarzCikAh.qqqqqqedbfOgqogbBBnneCyzuixfbdqnqqqqehgojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvrzCOkgh.qcsqqqedBAOBqqgbBAqsqmyzuixfbdqcsqqqedgfsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvrzCOkgheqccqqqedBAxhqqBbAf.sqzyzCixfbdqccqqqedbfsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvymCOkgh.qccqqqedBAkdqqhbptdsqzyzCixfbhqccqqqedbksjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvymCOkgh.qcsqqqedBAf.qqbbpxBsquyzuixfghqssqqqedbknjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjmvymCOkgh.qqqqqeedBAAqqeAbuibnquyzuixfgheqqqqqedbfnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjmvymCOkAB.eqqqqe.hbAgqqeAbrpgqnuyzupxkgB.qqqqqedbkojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvrzCOkABdeqqqee.hbwbqq.fbzufqnxyzupOkABdeqqqe.hgknjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvrzCitAbd.eeeeedBgxhqqdwbrmfesfrzupOkAbh.eeee.hgtsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnvrzuitfbh.eeee.dBAkdqqhgbyztdnbrzmCOtfbh.eee.dBAtsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvrzupxfgBd..e.dhbAf.qqbgbyrOBnqrymCixfgBd....hbAOjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjarympOkAbhd..dhBgfA.qeAgbyribqquymCixkAbhd..dhgfijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrvymCOtfgBhddhBbAxgeqetgbzvpAqqxyzupOkfgBhddhbAkijjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjyvrzuixfAbBhhBbgfxbqq.tgbrvuAeqbrzuCitfAbBhBBgfxnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvrzupOwfgbbBbgAxxBqqdtgbzamf.qqzymCixkfgbbbgAkinjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjvvymCixkfAgggAfpkhqqhAgbrazthqqOyzupOtkAAggAfxwjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsvrzupOtkfAAffxuf.qqbAgbzayOBqq.yzmCixtffAfftinjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjrrymCiOtkkkktCCA.qeAtgAraribqqeuyzupixtkkktOpjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjnrrzmCiOxttxOyigeqetiiOravpgqqqirzmCpixxxxOCnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjmvrzuCpiOOizrObqq.xCppvavCfeqqAryzmCpiiiiCnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzvyzmCCppCvyxBqqdpuuzaavmk.qqBrryzmuCpCuOjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjCvryzmmuuazkdqqhmzzraaazwdqqhrryyzmmmmnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjsCrrztgbvuf.qqgzyraavayxBqq.CiABtyzCsjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjuigeqvmkbqeAikxCzOvrikBqhxfdqeojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjzOBnovukBhfkAddpOgzvyiAhbOfqnqfjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjCpbeyrOBqqhthnqfkdzvukdqegkhe.ojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjszxAvyxhsq.khnqgkdzvCfesqbpfgfnjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjniOrrObeeBOgddiigzamkheeACCosjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjCuwggwmiwxpziCvypfgAojjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjCzCnsjnnjjsnnssCuinjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj",
"jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj"
};

static char *exit_in_icon [] = { 
"32 32 6 1",
"  c DodgerBlue",
". c #000000000000",
"o c #FFFFFFFFFFFF",
"O c Orange",
"a c Gold",
"b c firebrick",
"                                ",
"                                ",
"  .............                 ",
"  ..oooooooooo.                 ",
"  .O.aoaoaoaoa.                 ",
"  .bO.oaoaoaoa.   ...           ",
"  .ObO.oaoaoao.   ....          ",
"  .bObO.oaoaoa.  .....          ",
"  .ObObO.oaoao.  .....          ",
"  .bObOb.aoaoa.   ...           ",
"  .ObObO.oaoao....   .....      ",
"  .bObOb.aoaoa.............     ",
"  .ObObO.oaoao.   .....  ..     ",
"  .bObOb.aoaoa.     ...  ..     ",
"  .ObO.O.oaoao.     ...   ..    ",
"  .bOb.b.aoaoa.     ...   ..    ",
"  .ObObO.oaoao.     ...         ",
"  .bObOb.oaooa.    ....         ",
"  .ObObO.aaaaa.   ......   ..   ",
"  ..ObOb.......   ..  ... ....  ",
"    .ObO.aoaoao   ..   ..... .  ",
"     .Ob.oaoaoao ..     ...     ",
"      .O.aoaoaoao..             ",
"       ..oaoaoaoa..             ",
"         aoaoaoa...a            ",
"          aoaoaoaoaoaoa         ",
"           aoaoaoaoaoaoa        ",
"            aoaoaoaoaoaoaoa     ",
"             aoaoaoaoaoaoaoa    ",
"              aoaoaoaoaoaoaoa   ",
"               aoaoaoaoaoaoaoa  ",
"              aoaoaoaoaoaoaoaoa "
};

static char *exit_icon [] = { 
"32 32 6 1",
"  c DodgerBlue",
". c #000000000000",
"o c #FFFFFFFFFFFF",
"O c Orange",
"a c Gold",
"b c firebrick",
"                                ",
" .............                  ",
" ..oooooooooo.                  ",
" .O.aoaoaoaoa.                  ",
" .bO.oaoaoaoa.   ...            ",
" .ObO.oaoaoao.   ....           ",
" .bObO.oaoaoa.  .....           ",
" .ObObO.oaoao.  .....           ",
" .bObOb.aoaoa.   ...            ",
" .ObObO.oaoao....   .....       ",
" .bObOb.aoaoa.............      ",
" .ObObO.oaoao.   .....  ..      ",
" .bObOb.aoaoa.     ...  ..      ",
" .ObO.O.oaoao.     ...   ..     ",
" .bOb.b.aoaoa.     ...   ..     ",
" .ObObO.oaoao.     ...          ",
" .bObOb.oaooa.    ....          ",
" .ObObO.aaaaa.   ......   ..    ",
" ..ObOb.......   ..  ... ....   ",
"   .ObO.aoaoao   ..   ..... .   ",
"    .Ob.oaoaoao ..     ...      ",
"     .O.aoaoaoao..              ",
"      ..oaoaoaoa..              ",
"        aoaoaoa...a             ",
"         aoaoaoaoaoaoa          ",
"          aoaoaoaoaoaoa         ",
"           aoaoaoaoaoaoaoa      ",
"            aoaoaoaoaoaoaoa     ",
"             aoaoaoaoaoaoaoa    ",
"              aoaoaoaoaoaoaoa   ",
"             aoaoaoaoaoaoaoaoa  ",
"                                "
};

static char *copy_in_icon [] = { 
"32 32 5 1",
"  c #000000",
". c #4169E1",
"o c #FFEBCD",
"O c #FFFFFF",
"a c #CFCFCF",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaa        aaaaaaaaaaaaaaaaa",
"aaaaaa  oooooo aaaaaaaaaaaaaaaaa",
"aaaaa   oo   o aaaaaaaaaaaaaaaaa",
"aaaaa oooooooo aaaaaaaaaaaaaaaaa",
"aaaaa o  o  oo aa.aaaaaaaaaaaaaa",
"aaaaa oooooooo a...aaaaaaaaaaaaa",
"aaaaa o     oo aa...aa.aaaaaaaaa",
"aaaaa oooooooo aaa...a.aaaaaaaaa",
"aaaaa o o o  o aaaa....aaaaaaaaa",
"aaaaa oooooooo aaaaa...aaaaaaaaa",
"aaaaa o  o   o aaa.....aaaaaaaaa",
"aaaaa oooooooo aaaaaaaaaaaaaaaaa",
"aaaaa          aaaaaa        aaa",
"aaaaaaaaaaaaaaaaaaaa  OOOOOO aaa",
"aaaaaaaaaaaaaaaaaaa   OO   O aaa",
"aaaaaaaaaaaaaaaaaaa OOOOOOOO aaa",
"aaaaaaaaaaaaaaaaaaa O  O  OO aaa",
"aaaaaaaaaaaaaaaaaaa OOOOOOOO aaa",
"aaaaaaaaaaaaaaaaaaa O     OO aaa",
"aaaaaaaaaaaaaaaaaaa OOOOOOOO aaa",
"aaaaaaaaaaaaaaaaaaa O O O  O aaa",
"aaaaaaaaaaaaaaaaaaa OOOOOOOO aaa",
"aaaaaaaaaaaaaaaaaaa O  O   O aaa",
"aaaaaaaaaaaaaaaaaaa OOOOOOOO aaa",
"aaaaaaaaaaaaaaaaaaa          aaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
};

static char *copy_icon [] = { 
"32 32 5 1",
"  c #000000",
". c #4169E1",
"o c #FFEBCD",
"O c #FFFFFF",
"a c #CFCFCF",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaa        aaaaaaaaaaaaaaaaaa",
"aaaaa  oooooo aaaaaaaaaaaaaaaaaa",
"aaaa   oo   o aaaaaaaaaaaaaaaaaa",
"aaaa oooooooo aaaaaaaaaaaaaaaaaa",
"aaaa o  o  oo aa.aaaaaaaaaaaaaaa",
"aaaa oooooooo a...aaaaaaaaaaaaaa",
"aaaa o     oo aa...aa.aaaaaaaaaa",
"aaaa oooooooo aaa...a.aaaaaaaaaa",
"aaaa o o o  o aaaa....aaaaaaaaaa",
"aaaa oooooooo aaaaa...aaaaaaaaaa",
"aaaa o  o   o aaa.....aaaaaaaaaa",
"aaaa oooooooo aaaaaaaaaaaaaaaaaa",
"aaaa          aaaaaa        aaaa",
"aaaaaaaaaaaaaaaaaaa  OOOOOO aaaa",
"aaaaaaaaaaaaaaaaaa   OO   O aaaa",
"aaaaaaaaaaaaaaaaaa OOOOOOOO aaaa",
"aaaaaaaaaaaaaaaaaa O  O  OO aaaa",
"aaaaaaaaaaaaaaaaaa OOOOOOOO aaaa",
"aaaaaaaaaaaaaaaaaa O     OO aaaa",
"aaaaaaaaaaaaaaaaaa OOOOOOOO aaaa",
"aaaaaaaaaaaaaaaaaa O O O  O aaaa",
"aaaaaaaaaaaaaaaaaa OOOOOOOO aaaa",
"aaaaaaaaaaaaaaaaaa O  O   O aaaa",
"aaaaaaaaaaaaaaaaaa OOOOOOOO aaaa",
"aaaaaaaaaaaaaaaaaa          aaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
};

static char *open_in_icon [] = { 
"32 32 5 1",
"  c grey75",
". c #000000000000",
"o c #FFFFFFFF0000",
"O c #FFFFFFFFFFFF",
"a c DarkOliveGreen4",
"                                ",
"                                ",
"                                ",
"                                ",
"                                ",
"         .....                  ",
"        .oOOOo.                 ",
"      ..OOOoOOO...............  ",
"      .OOoOOOoOOOoOOOoOOOoOOO.  ",
"      .oOOOoOOOoOOOoOOOoOOOoO.  ",
"      .OOoOOOoOOOoOOOoOOOoOOO.  ",
"      .oOOOoOOOoOOOoOOOoOOOoO.  ",
"   ........................OO.  ",
"   .aoaoaoaoaoaoaoaoaoaoao.oO.  ",
"   .oaoaoaoaoaoaoaoaoaoaoa.OO.  ",
"   .aoaoaoaoaoaoaoaoaoaoao.oO.  ",
"    .aoaoaoaoaoaoaoaoaoaoao.O.  ",
"    .oaoaoaoaoaoaoaoaoaoaoa.O.  ",
"    .aoaoaoaoaoaoaoaoaoaoao.O.  ",
"    .oaoaoaoaoaoaoaoaoaoaoa.O.  ",
"     .oaoaoaoaoaoaoaoaoaoaoa..  ",
"     .aoaoaoaoaoaoaoaoaoaoao..  ",
"     .oaoaoaoaoaoaoaoaoaoaoa..  ",
"     .aoaoaoaoaoaoaoaoaoaoao..  ",
"      .aoaoaoaoaoaoaoaoaoaoao.  ",
"      .oaoaoaoaoaoaoaoaoaoaoa.  ",
"      .aoaoaoaoaoaoaoaoaoaoao.  ",
"      ........................  ",
"                                ",
"                                ",
"                                ",
"                                "
};

static char *open_icon [] = { 
"32 32 5 1",
"  c grey75",
". c #000000000000",
"o c #FFFFFFFF0000",
"O c #FFFFFFFFFFFF",
"a c DarkOliveGreen4",
"                                ",
"                                ",
"                                ",
"                                ",
"        .....                   ",
"       .oOOOo.                  ",
"     ..OOOoOOO...............   ",
"     .OOoOOOoOOOoOOOoOOOoOOO.   ",
"     .oOOOoOOOoOOOoOOOoOOOoO.   ",
"     .OOoOOOoOOOoOOOoOOOoOOO.   ",
"     .oOOOoOOOoOOOoOOOoOOOoO.   ",
"  ........................OO.   ",
"  .aoaoaoaoaoaoaoaoaoaoao.oO.   ",
"  .oaoaoaoaoaoaoaoaoaoaoa.OO.   ",
"  .aoaoaoaoaoaoaoaoaoaoao.oO.   ",
"   .aoaoaoaoaoaoaoaoaoaoao.O.   ",
"   .oaoaoaoaoaoaoaoaoaoaoa.O.   ",
"   .aoaoaoaoaoaoaoaoaoaoao.O.   ",
"   .oaoaoaoaoaoaoaoaoaoaoa.O.   ",
"    .oaoaoaoaoaoaoaoaoaoaoa..   ",
"    .aoaoaoaoaoaoaoaoaoaoao..   ",
"    .oaoaoaoaoaoaoaoaoaoaoa..   ",
"    .aoaoaoaoaoaoaoaoaoaoao..   ",
"     .aoaoaoaoaoaoaoaoaoaoao.   ",
"     .oaoaoaoaoaoaoaoaoaoaoa.   ",
"     .aoaoaoaoaoaoaoaoaoaoao.   ",
"     ........................   ",
"                                ",
"                                ",
"                                ",
"                                ",
"                                "
};


static void initialise_objects( Widget parent )
{
	XpmAttributes xpm_attributes;

	/* Some code to ensure that the pixmaps look OK even if the
	   color map is full or nearly so: */
	xpm_attributes.valuemask = XpmCloseness;
	xpm_attributes.closeness = 40000;
	if ( _xd_initialised ) return;
	_xd_initialised = 1;
	while ( XtParent ( parent ) )
		parent = XtParent ( parent );
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), kat_icon, &pixmap_resources.kat, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.kat = XmUNSPECIFIED_PIXMAP;
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), exit_in_icon, &pixmap_resources.exit_in, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.exit_in = XmUNSPECIFIED_PIXMAP;
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), exit_icon, &pixmap_resources.exit, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.exit = XmUNSPECIFIED_PIXMAP;
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), copy_in_icon, &pixmap_resources.copy_in, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.copy_in = XmUNSPECIFIED_PIXMAP;
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), copy_icon, &pixmap_resources.copy, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.copy = XmUNSPECIFIED_PIXMAP;
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), open_in_icon, &pixmap_resources.open_in, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.open_in = XmUNSPECIFIED_PIXMAP;
	if ( XpmCreatePixmapFromData( XtDisplay( parent ), DefaultRootWindow( XtDisplay( parent ) ), open_icon, &pixmap_resources.open, NULL, &xpm_attributes ) != 0 )
		pixmap_resources.open = XmUNSPECIFIED_PIXMAP;
}


void create_CopyShell (Widget parent)
{
	Widget children[2];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XmString xmstrings[16];    /* temporary storage for XmStrings */

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNminWidth, 300); ac++;
	XtSetArg(al[ac], XmNminHeight, 150); ac++;
	CopyShell = XmCreateDialogShell ( parent, "CopyShell", al, ac );
	ac = 0;
	initialise_objects ( CopyShell );
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	CopyForm = XmCreateForm ( CopyShell, "CopyForm", al, ac );
	ac = 0;
	xmstrings[0] = XmStringCreateLtoR ( "LiteClue_test Copy Dialog", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (CopyForm, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	CopyLabel = XmCreateLabel ( CopyForm, "CopyLabel", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNwidth, 70); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	xmstrings[0] = XmStringCreateLtoR ( "Ok", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (CopyForm, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	CopyOkBtn = XmCreatePushButton ( CopyForm, "CopyOkBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNtopOffset, 20); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 20); ac++;
	XtSetValues ( CopyLabel,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 10); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 10); ac++;
	XtSetValues ( CopyOkBtn,al, ac );
	ac = 0;
	XtAddCallback( CopyOkBtn, XmNactivateCallback, CopyOkBtn_cb, (XtPointer) 0 );
	children[ac++] = CopyLabel;
	children[ac++] = CopyOkBtn;
	XtManageChildren(children, ac);
	ac = 0;
}


void create_LiteClueTestShell (Display *display, char *app_name, int app_argc, char **app_argv)
{
	Widget children[4];      /* Children to manage */
	Arg al[64];                    /* Arg List */
	register int ac = 0;           /* Arg Count */
	XrmValue from_value, to_value; /* For resource conversion */
	XmString xmstrings[16];    /* temporary storage for XmStrings */
	Widget menuBar1 = (Widget)NULL;
	Widget label2 = (Widget)NULL;

	XtSetArg(al[ac], XmNallowShellResize, TRUE); ac++;
	XtSetArg(al[ac], XmNtitle, "LiteClue_test"); ac++;
	XtSetArg(al[ac], XmNminWidth, 300); ac++;
	XtSetArg(al[ac], XmNminHeight, 300); ac++;
	XtSetArg(al[ac], XmNargc, app_argc); ac++;
	XtSetArg(al[ac], XmNargv, app_argv); ac++;
	LiteClueTestShell = XtAppCreateShell ( app_name, "LiteClue_test", applicationShellWidgetClass, display, al, ac );
	ac = 0;
	initialise_objects ( LiteClueTestShell );
	if (DefaultDepthOfScreen(DefaultScreenOfDisplay(display)) != 1) {
	from_value.addr = "grey75";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (LiteClueTestShell, XmRString, &from_value, XmRPixel, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNbackground, *(unsigned int *)to_value.addr); ac++;
	}
	}
	XtSetValues ( LiteClueTestShell,al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNautoUnmanage, FALSE); ac++;
	MainForm = XmCreateForm ( LiteClueTestShell, "MainForm", al, ac );
	ac = 0;
	menuBar1 = XmCreateMenuBar ( MainForm, "MenuBar", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "File", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (menuBar1, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "F";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (menuBar1, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	FileCascade = XmCreateCascadeButton ( menuBar1, "FileCascade", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	FileMenu = XmCreatePulldownMenu ( menuBar1, "FileMenu", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "Open", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (FileMenu, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "O";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (FileMenu, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	FileOpenBtn = XmCreatePushButton ( FileMenu, "FileOpenBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Exit", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (FileMenu, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "x";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (FileMenu, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	FileExitBtn = XmCreatePushButton ( FileMenu, "FileExitBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Edit", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (menuBar1, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "E";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (menuBar1, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	EditCascade = XmCreateCascadeButton ( menuBar1, "EditCascade", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	EditMenu = XmCreatePulldownMenu ( menuBar1, "EditMenu", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "Cut", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (EditMenu, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "t";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (EditMenu, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	EditCutBtn = XmCreatePushButton ( EditMenu, "EditCutBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Copy", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (EditMenu, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "C";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (EditMenu, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	EditCopyBtn = XmCreatePushButton ( EditMenu, "EditCopyBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Paste", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (EditMenu, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "P";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (EditMenu, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	EditPasteBtn = XmCreatePushButton ( EditMenu, "EditPasteBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	xmstrings[0] = XmStringCreateLtoR ( "Help", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (menuBar1, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "H";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (menuBar1, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	HelpCascade = XmCreateCascadeButton ( menuBar1, "HelpCascade", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	HelpMenu = XmCreatePulldownMenu ( menuBar1, "HelpMenu", al, ac );
	xmstrings[0] = XmStringCreateLtoR ( "About", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (HelpMenu, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	from_value.addr = "A";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (HelpMenu, XmRString, &from_value, XmRKeySym, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNmnemonic, *(unsigned int *)to_value.addr); ac++;
	}
	HelpAboutBtn = XmCreatePushButton ( HelpMenu, "HelpAboutBtn", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNmenuHelpWidget, HelpCascade); ac++;
	XtSetValues ( menuBar1,al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 70); ac++;
	XtSetArg(al[ac], XmNheight, 35); ac++;
	xmstrings[0] = XmStringCreateLtoR ( "Quit", (XmStringCharSet)XmFONTLIST_DEFAULT_TAG );
	XtSetArg(al[ac], XmNlabelString, xmstrings[0]); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	from_value.addr = "-adobe-helvetica-bold-r-*-*-14-*-*-*-*-*-*-*";
	from_value.size = strlen( from_value.addr ) + 1;
	to_value.addr = NULL;
	XtConvertAndStore (MainForm, XmRString, &from_value, XmRFontList, &to_value);
	if ( to_value.addr )
	{
		XtSetArg(al[ac], XmNfontList, *(unsigned int *)to_value.addr); ac++;
	}
	QuitButton = XmCreatePushButton ( MainForm, "QuitButton", al, ac );
	ac = 0;
	XmStringFree ( xmstrings [ 0 ] );
	XtSetArg(al[ac], XmNshadowType, XmSHADOW_OUT); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 2); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 2); ac++;
	ToolbarFrame = XmCreateFrame ( MainForm, "ToolbarFrame", al, ac );
	ac = 0;
	ToolbarForm = XmCreateForm ( ToolbarFrame, "ToolbarForm", al, ac );
	XtSetArg(al[ac], XmNwidth, 37); ac++;
	XtSetArg(al[ac], XmNheight, 37); ac++;
	XtSetArg(al[ac], XmNhighlightThickness, 0); ac++;
	XtSetArg(al[ac], XmNlabelType, XmPIXMAP); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	ToolbarOpenBtn = XmCreatePushButton ( ToolbarForm, "ToolbarOpenBtn", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNlabelPixmap, pixmap_resources.open); ac++;
	XtSetArg(al[ac], XmNarmPixmap, pixmap_resources.open_in); ac++;
	XtSetValues ( ToolbarOpenBtn,al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 37); ac++;
	XtSetArg(al[ac], XmNheight, 37); ac++;
	XtSetArg(al[ac], XmNhighlightThickness, 0); ac++;
	XtSetArg(al[ac], XmNlabelType, XmPIXMAP); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	ToolbarCopyBtn = XmCreatePushButton ( ToolbarForm, "ToolbarCopyBtn", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNlabelPixmap, pixmap_resources.copy); ac++;
	XtSetArg(al[ac], XmNarmPixmap, pixmap_resources.copy_in); ac++;
	XtSetValues ( ToolbarCopyBtn,al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNwidth, 37); ac++;
	XtSetArg(al[ac], XmNheight, 37); ac++;
	XtSetArg(al[ac], XmNhighlightThickness, 0); ac++;
	XtSetArg(al[ac], XmNlabelType, XmPIXMAP); ac++;
	XtSetArg(al[ac], XmNrecomputeSize, FALSE); ac++;
	ToolbarExitBtn = XmCreatePushButton ( ToolbarForm, "ToolbarExitBtn", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNlabelPixmap, pixmap_resources.exit); ac++;
	XtSetArg(al[ac], XmNarmPixmap, pixmap_resources.exit_in); ac++;
	XtSetValues ( ToolbarExitBtn,al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNborderWidth, 2); ac++;
	XtSetArg(al[ac], XmNmarginWidth, 0); ac++;
	XtSetArg(al[ac], XmNmarginHeight, 0); ac++;
	XtSetArg(al[ac], XmNlabelType, XmPIXMAP); ac++;
	label2 = XmCreateLabel ( MainForm, "label2", al, ac );
	ac = 0;
	XtSetArg(al[ac], XmNlabelPixmap, pixmap_resources.kat); ac++;
	XtSetValues ( label2,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetValues ( menuBar1,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNbottomOffset, 10); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 10); ac++;
	XtSetValues ( QuitButton,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, menuBar1); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNrightOffset, 0); ac++;
	XtSetValues ( ToolbarFrame,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 20); ac++;
	XtSetArg(al[ac], XmNtopWidget, ToolbarFrame); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 70); ac++;
	XtSetValues ( label2,al, ac );
	ac = 0;
InstallLiteClues() ;
	XtAddCallback( FileExitBtn, XmNactivateCallback, QuitButton_cb, (XtPointer) 0 );
	children[ac++] = FileOpenBtn;
	children[ac++] = FileExitBtn;
	XtManageChildren(children, ac);
	ac = 0;
	XtSetArg(al[ac], XmNsubMenuId, FileMenu); ac++;
	XtSetValues ( FileCascade, al, ac );
	ac = 0;
	XtAddCallback( EditCopyBtn, XmNactivateCallback, EditCopyBtn_cb, (XtPointer) 0 );
	children[ac++] = EditCutBtn;
	children[ac++] = EditCopyBtn;
	children[ac++] = EditPasteBtn;
	XtManageChildren(children, ac);
	ac = 0;
	XtSetArg(al[ac], XmNsubMenuId, EditMenu); ac++;
	XtSetValues ( EditCascade, al, ac );
	ac = 0;
	children[ac++] = HelpAboutBtn;
	XtManageChildren(children, ac);
	ac = 0;
	XtSetArg(al[ac], XmNsubMenuId, HelpMenu); ac++;
	XtSetValues ( HelpCascade, al, ac );
	ac = 0;
	children[ac++] = FileCascade;
	children[ac++] = EditCascade;
	children[ac++] = HelpCascade;
	XtManageChildren(children, ac);
	ac = 0;
	XtAddCallback( QuitButton, XmNactivateCallback, QuitButton_cb, (XtPointer) 0 );

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_FORM); ac++;
	XtSetArg(al[ac], XmNleftOffset, 10); ac++;
	XtSetValues ( ToolbarOpenBtn,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, ToolbarOpenBtn); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNleftWidget, ToolbarOpenBtn); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( ToolbarCopyBtn,al, ac );
	ac = 0;

	XtSetArg(al[ac], XmNtopAttachment, XmATTACH_OPPOSITE_WIDGET); ac++;
	XtSetArg(al[ac], XmNtopOffset, 0); ac++;
	XtSetArg(al[ac], XmNtopWidget, ToolbarCopyBtn); ac++;
	XtSetArg(al[ac], XmNbottomAttachment, XmATTACH_NONE); ac++;
	XtSetArg(al[ac], XmNleftAttachment, XmATTACH_WIDGET); ac++;
	XtSetArg(al[ac], XmNleftOffset, 5); ac++;
	XtSetArg(al[ac], XmNleftWidget, ToolbarCopyBtn); ac++;
	XtSetArg(al[ac], XmNrightAttachment, XmATTACH_NONE); ac++;
	XtSetValues ( ToolbarExitBtn,al, ac );
	ac = 0;
	children[ac++] = ToolbarOpenBtn;
	children[ac++] = ToolbarCopyBtn;
	children[ac++] = ToolbarExitBtn;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = ToolbarForm;
	XtManageChildren(children, ac);
	ac = 0;
	children[ac++] = menuBar1;
	children[ac++] = QuitButton;
	children[ac++] = ToolbarFrame;
	children[ac++] = label2;
	XtManageChildren(children, ac);
	ac = 0;
	XtManageChild ( MainForm);
}



XtAppContext app_context;
Display *display;       /*  Display             */

int main (int argc, char **argv)
{
	XtSetLanguageProc ( (XtAppContext) NULL, (XtLanguageProc) NULL, (XtPointer) NULL );
	XtToolkitInitialize ();
	app_context = XtCreateApplicationContext ();
	display = XtOpenDisplay (app_context, NULL, argv[0], "LiteClue_test",
	                         NULL, 0, &argc, argv);
	if (!display)
	{
	    printf("%s: can't open display, exiting...\n", argv[0]);
	    exit (-1);
	}
	create_LiteClueTestShell ( display, argv[0], argc, argv );
	create_CopyShell ( LiteClueTestShell );
	XtRealizeWidget (LiteClueTestShell);
	XtAppMainLoop (app_context);
	exit (0);
}

