...\" ** $Id: XltCreateBubbleButton.3.in,v 1.1 2001/06/22 21:38:52 amai Exp $
...\" **
.TH XltCreateBubbleButton 3X "" "" "" ""
.ds )H Rick Scott
.ds ]W Xlt Version 13.0.13
.SH NAME
\fIXltCreateBubbleButton\fP \- Convenience function to create a BubbleButton widget
.SH SYNOPSIS
.nf
.sS
.iS
\&#include <Xlt/BubbleButton.h>
.sp \n(PDu
Widget XltCreateBubbleButton(\fBparent, name, arglist, argcount\fI)
.ta .5i 1.5i
.nf
	Widget	\fBparent\fI;
	String	\fBname\fI;
	ArgList	\fBarglist\fI;
	Cardinal	\fBargcount\fI;
.wH
.fi
.iE
.sE
.SH DESCRIPTION
.fi
\fIXltCreateBubbleButton\fP create an instance of a BubbleButton widget and
returns the associated widget ID.
.IP "\fBparent\fP"
The parent widget ID
.IP "\fBname\fP"
The widget name.
.IP "\fBarglist\fP"
The arglist.
.IP "\fBargcount\fP"
The number of args in arglist.
.PP 
For a complete description of BubbleButton, see
\fIXltBubbleButton(3X)\fP
.SH RETURN VALUE
Returns the BubbleButton widget ID.
.SH RELATED INFORMATION
.na
\fIXltBubbleButton(3X)\fP.
.ad
