...\" ** $Id: XltToolBarAddItem.3.in,v 1.1 2001/06/25 14:11:39 amai Exp $
...\" **
.TH XltToolBarAddItem 3X "" "" "" ""
.ds )H Rick Scott
.ds ]W Xlt Version 13.0.13
.SH NAME
\fIXltToolBarAddItem\fP \- Convenience function to bring up a YesNo dialog.
.SH SYNOPSIS
.nf
.sS
.iS
\&#include <Xlt/Xlt.h>
.sp \n(PDu
Widget 
XltToolBarAddItem(Widget ToolBar, char *Label, char **PixmapData)
.wH
.fi
.iE
.sE
.SH DESCRIPTION
.fi
\fIXltToolBarAddItem\fP 
.PP 
.SH RETURN VALUE
.SH RELATED INFORMATION
.na
.ad
