/*
** Generated by X-Designer
*/
#ifndef _main_h
#define _main_h

#define XD_MOTIF



extern Widget toplevel;
extern Widget inW;
extern Widget outW;

extern void create_toplevel (Display *, char *, int, char **);




/* Global Variables Generated into Main Module */

extern XtAppContext app_context ;
extern Display     *display ;


#endif
