"MXkill*psCommand: /bin/ps",
"MXkill*psdefOption: ea|sort +0 -1",
"MXkill*psAllOption: eax",
"MXkill*psAllbyUserOption: eaxu|sort +0 -1",
"MXkill*psAllbyPidOption: eaxu|sort -n +1 -2",
"MXkill*background: gray",
"MXkill*foreground: Black",
"MXkill*highlightColor: Red",
"MXkill*highlightThickness: 1",
"MXkill*menuBar*fontList: *helvetica-medium-r-normal--12*",
"MXkill*XmText*background: #d3b5b5",
"MXkill*XmText*foreground: black",
"MXkill*XmPushButton.fontList: *helvetica-medium-r-normal--12*",
"MXkill*XmPushButtonGadget.fontList: *helvetica-medium-r-normal--12*",
"MXkill*XmPushButton*alignment: ALIGNMENT_CENTER",
"MXkill*XmPushButtonGadget*alignment: ALIGNMENT_CENTER",
"MXkill*XmLabel.fontList: *helvetica-bold-r-*-140*",
"MXkill*XmLabel.fontList: *helvetica-medium-r-normal--12*",
"MXkill*XmLabelGadget.fontList: *helvetica-medium-r-normal--12*",
"MXkill*xpslist.height: 500",
"MXkill*xpslist*fontList: fixed",
"MXkill*xpslist*background: white",
"MXkill*xpslist*foreground: black",
"MXkill*xpstext*background: #d3b5b5",
"MXkill*xpstext*columns: 50",
"MXkill*xpsheadtext*highlightThickness: 0",
"MXkill*xpsheadtext*cursorPositionVisible: False",
"MXkill*xpsheadtext*editable: False",
"MXkill*xpsheadtext*background: black",
"MXkill*xpsheadtext*foreground: yellow",
"MXkill*xpsheadtext*fontList: -*-fixed-medium-r-*-*-12-*",
"MXkill*xwclab.labelString: Regular Expression:",
"MXkill*xwctext*background: #d3b5b5",
"MXkill*xwctext*foreground: black",
"MXkill*xwctext*columns: 50",
"MXkill*xwcframe*shadowType: shadow_out",
"MXkill*aboutd.messageAlignment: alignment_center",
"MXkill*aboutd*fontList: lucidasans-12,lucidasans-bold-12=BOLD,lucidasans-bold-18=BIG,lucidasans-10=SMALL,lucidasans-italic-12=ITALIC",
"MXkill*aboutd.messageString:\
<BIG>mxkill Release 1.1<>\\n\
<SMALL>[Labor Day Weekend, 1995]<>\\n\
\\n\
X/Motif interface to ps\\n\
By\\n\
<ITALIC>Muhammad A. Muquit<>\\n\
\\n\
http://www.semcor.com/~muquit/\\n\
<BOLD>Email: <SMALL>muquit@semcor.com",
"MXkill*msgframew.shadowType: SHADOW_ETCHED_OUT",
"MXkill*msgframew.shadowThickness: 2",
"MXkill*msgtextw*fontList: *helvetica-medium-r-normal--12*",
"MXkill*msgtextw.marginHeight: 0",
"MXkill*msgtextw.highlightThickness: 0",
"MXkill*msgrcw*background: black",
"MXkill*msgrcw*foreground: white",
