#!/bin/sh
# @(#)$Mu: tools/sgmlpp 1.5 1998/08/21 05:59:16 $
##
## sgmlpp
##	Simple SGML preprocessor for documentation.
##
## Copyright (C) 1996  Eric A. Howe
##
## This program is free software; you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation; either version 2 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
##
##   Authors:	Matthew D. Francey
##		Eric A. Howe (mu@trends.net)
##
version=$1;	shift

##
## Automake was doing bad things to this substitution (the final $/ was
## disappearing so it goes in a separate script as a work-around.
##
sed	-e '/^<date>/s/\$\Date: \([0-9\/][0-9\/]*\) .*\$/\1/g' \
	-e "s/__VERSION__/$version/g"
