/* Generated by wbuild from "EntrySB.w"
** (generator version $Revision: 1.1 $ of $Date: 1998/06/30 23:13:09 $)
*/
#ifndef _XltEntrySBP_H_
#define _XltEntrySBP_H_
#include <Xm/ManagerP.h>
#include <./EntrySB.h>
_XFUNCPROTOBEGIN
typedef struct {
/* Constraint resources */
/* Private constraint variables */
int dummy;
} XltEntrySBConstraintPart;

typedef struct _XltEntrySBConstraintRec {
XmManagerConstraintPart xmManager;
XltEntrySBConstraintPart xltEntrySB;
} XltEntrySBConstraintRec;


typedef struct {
/* methods */
/* class variables */
int dummy;
} XltEntrySBClassPart;

typedef struct _XltEntrySBClassRec {
CoreClassPart core_class;
CompositeClassPart composite_class;
ConstraintClassPart constraint_class;
XmManagerClassPart xmManager_class;
XltEntrySBClassPart xltEntrySB_class;
} XltEntrySBClassRec;

typedef struct {
/* resources */
String  minval;
String  maxval;
int  decimals;
String  value;
Dimension  scrollWidth;
int  textWidth;
String  label;
XtCallbackList  valueChanged;
/* private state */
Widget  scrollbar;
Widget  text;
Widget  label_widget;
int  manual_update;
float  internal_min;
float  internal_max;
float  internal_value;
char  value_buf[25];
} XltEntrySBPart;

typedef struct _XltEntrySBRec {
CorePart core;
CompositePart composite;
ConstraintPart constraint;
XmManagerPart xmManager;
XltEntrySBPart xltEntrySB;
} XltEntrySBRec;

externalref XltEntrySBClassRec xltEntrySBClassRec;

_XFUNCPROTOEND
#endif /* _XltEntrySBP_H_ */
