/* Generated by wbuild from "EntrySB.w"
** (generator version $Revision: 1.1 $ of $Date: 1998/06/30 23:13:08 $)
*/
#ifndef _XltEntrySB_H_
#define _XltEntrySB_H_
_XFUNCPROTOBEGIN
#ifndef XtNminval
#define XtNminval "minval"
#endif
#ifndef XtCMinval
#define XtCMinval "Minval"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNmaxval
#define XtNmaxval "maxval"
#endif
#ifndef XtCMaxval
#define XtCMaxval "Maxval"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNdecimals
#define XtNdecimals "decimals"
#endif
#ifndef XtCDecimals
#define XtCDecimals "Decimals"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNvalue
#define XtNvalue "value"
#endif
#ifndef XtCValue
#define XtCValue "Value"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNscrollWidth
#define XtNscrollWidth "scrollWidth"
#endif
#ifndef XtCScrollWidth
#define XtCScrollWidth "ScrollWidth"
#endif
#ifndef XtRDimension
#define XtRDimension "Dimension"
#endif

#ifndef XtNtextWidth
#define XtNtextWidth "textWidth"
#endif
#ifndef XtCTextWidth
#define XtCTextWidth "TextWidth"
#endif
#ifndef XtRInt
#define XtRInt "Int"
#endif

#ifndef XtNlabel
#define XtNlabel "label"
#endif
#ifndef XtCLabel
#define XtCLabel "Label"
#endif
#ifndef XtRString
#define XtRString "String"
#endif

#ifndef XtNvalueChanged
#define XtNvalueChanged "valueChanged"
#endif
#ifndef XtCValueChanged
#define XtCValueChanged "ValueChanged"
#endif
#ifndef XtRCallback
#define XtRCallback "Callback"
#endif

typedef struct _XltEntrySBClassRec *XltEntrySBWidgetClass;
typedef struct _XltEntrySBRec *XltEntrySBWidget;
externalref WidgetClass xltEntrySBWidgetClass;
_XFUNCPROTOEND
#endif /*_XltEntrySB_H_*/
